### ISSUE TITLE
Fire on Rock

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/iThrowRock#1]
it would be cool to have fire come out of the rock when velocity is high.

**Comment by pgonzbecer** [comment]
Trailing is up, but I need a fire texture for it.

**Comment by johnRedden** [comment]
I don't get the reasoning behind the distance between the x and y velocities... but cool nonetheless!  Perhaps just turn on fire trailing when the y-velocity is fast enough to break bottles... like -1200 or something... only going up.

Also, I had no idea that spriteBatch existed... what is that?  Can we scale down trailing sprites individually big to small?  Also, does the removeChildAt destroy the sprite?

**Comment by johnRedden** [comment]
Oh I see how this works... scaling will be hard.  Maybe the trailing fire sprite should be an animated sprite sheet... fire, smaller, smaller fire, super small fire then a puff of smoke.  When the temp sprite is instantiated you run the animation?  The timing will be hard.

**Comment by pgonzbecer** [comment]
@johnRedden Answers to your questions,
- The distance thing just gets the length/magnitude of a vector. So that way it is always positive and affects for both the x and y axis
- A sprite batch is a group of sprites, it is used to render the sprites at a better performance rate than just a regular group or array.
- I tried scaling over time, doesn't work well. At least there is not a setInterval for the Phaser timer that I can see.
- I couldn't get it to delete and resize without crashing and within the time frame of when I was doing it. But when there is a new trailing going on, it deletes all the old ones.

@mecharmor You hear that we are going to need a scaling fire spritesheet.

**Comment by johnRedden** [comment]
Oh yes, magnitude of the velocity vector is better... maybe we call it that?   I do think a fire sprite sheet will finish this off.

**Comment by pgonzbecer** [comment]
Great job Cory. It looks amazing!
